import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from "next/font/google";
import NextTopLoader from "nextjs-toploader";

import { Toaster } from "@/components/ui/toaster";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: {
    template: "%s | Payung Proteksi",
    default: "Payung Proteksi",
  },
  description: "Generated by create next app",
  icons: {
    icon: "/assets/images/logo.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.variable}>
        <NextTopLoader color="#624CF5" />
        {children}
        <Toaster />
        <div id="modal-root" />
      </body>
    </html>
  );
}
